### ISSUE TITLE
Motor contenders

### ISSUE THREAD

**Issue by nammenam** [fest004/Cubitron#1]
https://www.maxongroup.com/maxon/view/product/397172

**Comment by fest004** [comment]
We need: 

Torque >= 50mNm 
Diameter ~80mm or less 
Reasonable power needs (30-50 watt) 
Hall sensor or other speed/positional trackers

**Comment by nammenam** [comment]
https://www.maxongroup.com/maxon/view/product/397172

**Comment by nammenam** [comment]
https://www.maxongroup.com/maxon/view/product/200142

**Comment by nammenam** [comment]
options:

https://no.rs-online.com/web/p/dc-motors/2163787

https://no.farnell.com/en-NO/nanotec/df45m024053-a2/bldc-motor-24vdc-6700rpm/dp/2507572?gross_price=true&CMP=KNC-GNO-GEN-Shopping-Pmax-16th-Nov-2023&mckv=_dc%7Cpcrid%7C%7C&gad_source=1&gclid=Cj0KCQjwrp-3BhDgARIsAEWJ6SzON5sbiG9MOx16bTlnzHi62jj08H952yAhyp4njKd3F_feWO3J-v8aAs1GEALw_wcB

https://www.ebay.co.uk/itm/225609556846?chn=ps&_ul=GB&_trkparms=ispr%3D1&amdata=enc%3A15b0aM6_wQKKjIRZzB3Sezw25&norover=1&mkevt=1&mkrid=710-169684-097358-0&mkcid=2&itemid=225609556846&targetid=325425753764&device=c&mktype=pla&googleloc=9192944&poi=&campaignid=20649918451&mkgroupid=151788312862&rlsatarget=pla-325425753764&abcId=&merchantid=114962777&gad_source=1&gclid=Cj0KCQjwrp-3BhDgARIsAEWJ6SzzDTp3XYysUq8rXY8LX0oyRT4pCRK1imTXJrdODRe665h0yRkFqCUaApNFEALw_wcB

Great website for browsing: https://no.rs-online.com/web/

**Comment by nammenam** [comment]
https://mechtex.com/products/bldc-motors/bo42-50w

**Comment by nammenam** [comment]
@fest004 comment the motor we have decided on and close this issue

**Comment by fest004** [comment]
https://www.maxongroup.com/maxon/view/product/200142 This is the motor we have decided on. Waiting to order 3.

**Comment by fest004** [comment]
https://no.rs-online.com/web/p/dc-motors/2163794?gb=s is the actual correct motor.

**Comment by fest004** [comment]
Closed

**Comment by nammenam** [comment]
catalog for maxon motors
page 67 talks about hall sensors

https://online.flippingbook.com/view/1042987/67/#zoom=true
