### ISSUE TITLE
Transistors

### ISSUE THREAD

**Issue by fest004** [fest004/Cubitron#14]
Choose transistors for motors

**Comment by fest004** [comment]
https://no.mouser.com/ProductDetail/Vishay-Semiconductors/SI4532CDY-T1-GE3?qs=45wPT2wjtGnob1HAmZ9n7g%3D%3D 

Dual N and P channel MOSFET transistors.

**Comment by nammenam** [comment]
changed the transistors to allow 12v gate voltage, this way we dont have to regulate down to 8V

**Comment by nammenam** [comment]
the transistors i added might have too low drain current but there is a version with a larger one we can switch too if it burns up

**Comment by nammenam** [comment]
closing this in favour of #8
